# Generated by Django 5.0.7 on 2025-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='biografias/')),
                ('descripcion', models.TextField()),
                ('discografia', models.TextField(blank=True, null=True)),
                ('premios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
